site_name: Manuale Manutentore | Stalker
repo_url: https://github.com/qb-team/Stalker-Documentazione/

theme:
  name: material
  custom_dir: "docs_theme"

markdown_extensions:
  # https://github.com/g-provost/lightgallery-markdown
  - lightgallery
  # https://squidfunk.github.io/mkdocs-material/extensions/admonition/
  - admonition
  # https://squidfunk.github.io/mkdocs-material/extensions/codehilite/
  - codehilite 

nav:
  - Registro modifiche: "registromodifiche.md"
  - Il gruppo qbteam: "qbteam.md"
  - 1 Indroduzione: "index.md"
  - 2 App utenti:
      - 2.1 Introduzione: "app/introduzione.md"
      - 2.2 Requisiti e installazione: "app/requisiti.md"
      - 2.3 Estendibilità: "app/estendibilita.md"
      - 2.4 Architettura: "app/architettura.md"
      - 2.5 Package: "app/package.md"
      - 2.6 Diagrammi delle classi: "app/classi.md"
      - 2.7 Diagrammi di sequenza: "app/sequenza.md"
  - 3 Web-app amministratori:
      - 3.1 Introduzione: "webapp/introduzione.md"
      - 3.2 Requisiti e installazione: "webapp/requisiti.md"
      - 3.3 Estendibilità: "webapp/estendibilita.md"
      - 3.4 Architettura: "webapp/architettura.md"
      - 3.5 Package: "webapp/package.md"
      - 3.6 Diagrammi delle classi: "webapp/classi.md"
      - 3.7 Diagrammi di sequenza: "webapp/sequenza.md"
  - 4 Backend:
      - 4.1 Introduzione: "backend/introduzione.md"
      - 4.2 Requisiti e installazione: "backend/requisiti.md"
      - 4.3 Estendibilità: "backend/estendibilita.md"
      - 4.4 Architettura: "backend/architettura.md"
      - 4.5 Package: "backend/package.md"
      - 4.6 Diagrammi delle classi: "backend/classi.md"
      - 4.7 Diagrammi di sequenza: "backend/sequenza.md"
  - 5 REST API:
      - 5.1 Introduction [EN]: "restapi/introduction.md"
      #- Specifica OpenAPI e Swagger: "restapi/openapi.md"
      # - 5.2 Utilizzo: "restapi/utilizzo.md"
      - 5.2 Overview [EN]: "restapi/overview.md"
      - 5.3 Model [EN]:
        - AdministratorBindingRequest: "restapi/model/AdministratorBindingRequest.md"
        - Favorite: "restapi/model/Favorite.md"
        - OrganizationAccess: "restapi/model/OrganizationAccess.md"
        - Organization: "restapi/model/Organization.md"
        - OrganizationMovement: "restapi/model/OrganizationMovement.md"
        - OrganizationPresenceCounter: "restapi/model/OrganizationPresenceCounter.md"
        - Permission: "restapi/model/Permission.md"
        - PlaceAccess: "restapi/model/PlaceAccess.md"
        - Place: "restapi/model/Place.md"
        - PlaceMovement: "restapi/model/PlaceMovement.md"
        - PlacePresenceCounter: "restapi/model/PlacePresenceCounter.md"
        - TimePerUserReport: "restapi/model/TimePerUserReport.md"
      - 5.4 Api [EN]:
        - AccessApi: "restapi/api/AccessApi.md"
        - AdministratorApi: "restapi/api/AdministratorApi.md"
        - FavoriteApi: "restapi/api/FavoriteApi.md"
        - MovementApi: "restapi/api/MovementApi.md"
        - OrganizationApi: "restapi/api/OrganizationApi.md"
        - PlaceApi: "restapi/api/PlaceApi.md"
        - PresenceApi: "restapi/api/PresenceApi.md"
        - ReportApi: "restapi/api/ReportApi.md"
  - A Glossario: "glossario.md"